apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-vsphere-controller
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vsphere-controller
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vsphere-controller
subjects:
  - kind: ServiceAccount
    name: csi-vsphere-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: csi-vsphere-controller
  apiGroup: rbac.authorization.k8s.io
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-vsphere-controller
spec:
  serviceName: csi-vsphere-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-vsphere-controller
    spec:
      serviceAccount: csi-vsphere-controller
      containers:
        - name: csi-attacher
          image: docker.io/cduchesne/csi-attacher
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--dummy"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
        - name: csi-provisioner
          image: docker.io/cduchesne/csi-provisioner
          args:
            - "--provisioner=csi-vsphere"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--volume-name-prefix=csivol"
            - "--volume-name-uuid-length=10"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
        - name: csi-vsphere
          image: docker.io/cduchesne/csi-vsphere
          command: [ "/csi-vsphere" ]
          env:
            - name: CSI_ENDPOINT
              value: /var/run/csi/csi.sock
            - name: X_CSI_DEBUG
              value: "true"
            - name: X_CSI_VSPHERE_DATASTORE
              value: datastore
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
      volumes:
        - name: socket-dir
          emptyDir:
